parameters:
#    algo_site.example.class: Algo\SiteBundle\Example

services:
#    algo_site.example:
#        class: %algo_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]services:
    algo_user.registration.form.type:
        class: Algo\SiteBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: algo_user_registration }
