algo_site:
    resource: "@AlgoSiteBundle/Resources/config/routing.yml"
    prefix:   /


#login:
 #   pattern:   /login
  #  defaults:  { _controller: AlgoSiteBundle:Security:login }
    
#register:
 #   pattern:   /register
  #  defaults:  { _controller: AlgoSiteBundle:Registration:register }
    
#logout:
 #   pattern:   /logout
    
    
#profile:
 #   pattern:   /profile
  #  defaults:  { _controller: AlgoSiteBundle:Profile:show }  
    
#login_check:
 #  pattern:   /login_check
  # defaults:  { _controller: FOSUserBundle:Security:login }




# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal


#FOS User Management Configuration
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

