# app/config/security.yml
security:
    firewalls:
        #secured_area:
         #   pattern:    ^/
          #  anonymous: ~
           # form_login:
            #    login_path:  login
             #   check_path:  login_check
        main:
              pattern: ^/
              form_login:
                  provider: fos_userbundle
                  login_path:  fos_user_security_login
                  check_path:  fos_user_security_check
                  csrf_provider: form.csrf_provider
                
              logout: 
                  path: /logout
                  target: /
              
                
                
              anonymous:  ~
                
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        #in_memory:
         #   memory:
          #      users:
           #         ryan:  { password: ryanpass, roles: 'ROLE_USER' }
            #        admin: { password: dn, roles: 'ROLE_ADMIN' }
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN